/**
 * Seed AI_Agents and AI_Playbooks sheets with initial data
 */
import type { GoogleSheetsService } from './sheets';

export const AI_AGENTS_SEED = [
  {
    AgentID: 'A-MGR-000',
    Name: 'Orchestrator',
    Department: 'Supervisor',
    Description: 'Route jobs & health',
    TasksJSON: '[]',
    GuardrailsJSON: '["no-direct-prod-writes"]',
    RequiresApproval: false,
    ModelSettings: JSON.stringify({ model: 'gpt-4o-mini', temperature: 0.3 }),
    Active: true,
    ScheduleCron: '0 8 * * *',
    Notes: 'Route jobs & health',
  },
  {
    AgentID: 'A-PRC-100',
    Name: 'Pricing Analyst',
    Department: 'Pricing',
    Description: 'Reprice & MAP guard',
    TasksJSON: JSON.stringify(['suggest-price-changes', 'analyze-competitive-pricing', 'validate-map-compliance']),
    GuardrailsJSON: JSON.stringify(['MAP', 'FloorMargin', 'PromoCap']),
    RequiresApproval: true,
    ModelSettings: JSON.stringify({ model: 'gpt-4o-mini', temperature: 0.5 }),
    Active: true,
    ScheduleCron: '15 8 * * *',
    Notes: 'Reprice & MAP guard',
  },
  {
    AgentID: 'A-OUT-101',
    Name: 'Outreach Writer',
    Department: 'Growth',
    Description: 'Email templates & sequences',
    TasksJSON: JSON.stringify(['generate-email-template', 'create-sequence', 'suggest-followup']),
    GuardrailsJSON: JSON.stringify(['GDPR', 'BrandVoice', 'RateLimit']),
    RequiresApproval: true,
    ModelSettings: JSON.stringify({ model: 'gpt-4o-mini', temperature: 0.7 }),
    Active: true,
    ScheduleCron: undefined,
    Notes: 'Email templates & sequences',
  },
  {
    AgentID: 'A-SOC-102',
    Name: 'Social Producer',
    Department: 'Marketing',
    Description: '14-day calendar',
    TasksJSON: JSON.stringify(['suggest-post', 'plan-calendar', 'generate-captions']),
    GuardrailsJSON: JSON.stringify(['BrandVoice']),
    RequiresApproval: true,
    ModelSettings: JSON.stringify({ model: 'gpt-4o-mini', temperature: 0.8 }),
    Active: true,
    ScheduleCron: '0 9 * * 1',
    Notes: '14-day calendar',
  },
  {
    AgentID: 'A-SEO-103',
    Name: 'SEO Architect',
    Department: 'Marketing',
    Description: 'Keywords & meta/schema',
    TasksJSON: JSON.stringify(['harvest-keywords', 'analyze-serp', 'suggest-content']),
    GuardrailsJSON: JSON.stringify(['NoBlackHat']),
    RequiresApproval: true,
    ModelSettings: JSON.stringify({ model: 'gpt-4o-mini', temperature: 0.6 }),
    Active: true,
    ScheduleCron: '0 10 * * 2',
    Notes: 'Keywords & meta/schema',
  },
  {
    AgentID: 'A-CRM-104',
    Name: 'CRM Enricher',
    Department: 'Sales',
    Description: 'Harvest & enrich salon leads',
    TasksJSON: JSON.stringify(['enrich-lead', 'assign-territory', 'score-lead', 'harvest-places']),
    GuardrailsJSON: JSON.stringify(['GDPR']),
    RequiresApproval: true,
    ModelSettings: JSON.stringify({ model: 'gpt-4o-mini', temperature: 0.4 }),
    Active: true,
    ScheduleCron: '0 11 * * 3',
    Notes: 'Harvest & enrich salon leads',
  },
  {
    AgentID: 'A-ADS-105',
    Name: 'Ads Strategist',
    Department: 'Marketing',
    Description: 'Google Ads CSV & negatives',
    TasksJSON: JSON.stringify(['generate-ads-csv', 'suggest-negatives', 'optimize-bids']),
    GuardrailsJSON: JSON.stringify(['BudgetCap', 'BrandVoice']),
    RequiresApproval: true,
    ModelSettings: JSON.stringify({ model: 'gpt-4o-mini', temperature: 0.6 }),
    Active: true,
    ScheduleCron: '0 10 * * 4',
    Notes: 'Google Ads CSV & negatives',
  },
  {
    AgentID: 'A-ECM-106',
    Name: 'Merchandiser',
    Department: 'Ecom',
    Description: 'Catalog audit & sync fixes',
    TasksJSON: JSON.stringify(['audit-catalog', 'suggest-fixes', 'sync-queue']),
    GuardrailsJSON: JSON.stringify(['NoDirectProdWrite']),
    RequiresApproval: true,
    ModelSettings: JSON.stringify({ model: 'gpt-4o-mini', temperature: 0.5 }),
    Active: true,
    ScheduleCron: '0 12 * * *',
    Notes: 'Catalog audit & sync fixes',
  },
];

export const AI_PLAYBOOKS_SEED = [
  {
    PlaybookID: 'PB-PRC-001',
    Name: 'Reprice All',
    AgentID: 'A-PRC-100',
    TriggerType: 'SCHEDULED',
    Cron: '15 8 * * *',
    SourceSheet: 'FinalPriceList',
    TargetSheet: 'Pricing_Suggestions_Draft',
    PromptTemplate: 'reprice_by_params_map',
    Active: true,
    Notes: 'Global reprice w/ MAP',
  },
  {
    PlaybookID: 'PB-OUT-010',
    Name: 'Template Pack',
    AgentID: 'A-OUT-101',
    TriggerType: 'MANUAL',
    Cron: undefined,
    SourceSheet: 'Outreach_Templates',
    TargetSheet: '',
    PromptTemplate: 'write_3_stage_intro',
    Active: true,
    Notes: '3-email intro pack',
  },
  {
    PlaybookID: 'PB-SOC-020',
    Name: '14d Calendar',
    AgentID: 'A-SOC-102',
    TriggerType: 'SCHEDULED',
    Cron: '0 9 * * 1',
    SourceSheet: 'FinalPriceList',
    TargetSheet: 'Social_Calendar_Draft',
    PromptTemplate: 'calendar_14d_beardcare',
    Active: true,
    Notes: 'Posts DE/EN',
  },
  {
    PlaybookID: 'PB-SEO-030',
    Name: 'Keyword Cluster',
    AgentID: 'A-SEO-103',
    TriggerType: 'MANUAL',
    Cron: undefined,
    SourceSheet: 'FinalPriceList',
    TargetSheet: 'SEO_Keywords_Draft',
    PromptTemplate: 'keyword_cluster_intent',
    Active: true,
    Notes: 'Buyer intent DE',
  },
  {
    PlaybookID: 'PB-CRM-040',
    Name: 'Harvest Berlin+HH',
    AgentID: 'A-CRM-104',
    TriggerType: 'SCHEDULED',
    Cron: '0 11 * * 3',
    SourceSheet: 'CRM_Leads',
    TargetSheet: 'CRM_Leads_Draft',
    PromptTemplate: 'harvest_places_salon_de',
    Active: true,
    Notes: '200 leads/week',
  },
  {
    PlaybookID: 'PB-ADS-050',
    Name: 'Ads CSV',
    AgentID: 'A-ADS-105',
    TriggerType: 'MANUAL',
    Cron: undefined,
    SourceSheet: 'SEO_Keywords',
    TargetSheet: 'Ads_Campaigns_Draft',
    PromptTemplate: 'ads_csv_builder',
    Active: true,
    Notes: 'Google Ads export',
  },
];

export async function seedAIAgents(sheetsService: GoogleSheetsService): Promise<void> {
  console.log('[Seed] Importing AI_Agents...');
  await sheetsService.writeRows('AI_Agents', AI_AGENTS_SEED);
  console.log(`[Seed] Imported ${AI_AGENTS_SEED.length} agents`);
}

export async function seedAIPlaybooks(sheetsService: GoogleSheetsService): Promise<void> {
  console.log('[Seed] Importing AI_Playbooks...');
  await sheetsService.writeRows('AI_Playbooks', AI_PLAYBOOKS_SEED);
  console.log(`[Seed] Imported ${AI_PLAYBOOKS_SEED.length} playbooks`);
}
