/**
 * Outreach Agent - A-OUT-101
 * Generates personalized outreach emails and manages campaigns
 */

import { nanoid } from 'nanoid';
import type { GoogleSheetsService } from '../sheets';
import { runGuardrails } from '../ai-guardrails';
import { createDraftJob } from '../ai-approval-workflow';

export interface EmailTemplateInput {
  name: string;
  subject: string;
  targetAudience: string;
  tone: 'professional' | 'friendly' | 'playful';
  locale: 'en' | 'de';
}

/**
 * Task: generate-email-template
 * Creates a new outreach email template
 */
export async function generateEmailTemplate(
  sheetsService: GoogleSheetsService,
  input: EmailTemplateInput
): Promise<{ jobId: string; template: any; guardrailsPassed: boolean }> {
  const now = new Date().toISOString();

  // 1. Generate template content (simplified - in real version would call OpenAI GPT-4)
  const unsubscribeLink = '{{UnsubscribeURL}}';
  const templateBody = `Dear {{FirstName}},\n\nWe noticed you're in the ${input.targetAudience} space...\n\nBest regards,\nYour Team\n\n---\nTo unsubscribe, click here: ${unsubscribeLink}`;

  const template = {
    TemplateID: `TPL-${nanoid(8)}`,
    JobID: '', // Will be set below
    Name: input.name,
    Subject: input.subject,
    Body: templateBody,
    TokensCSV: 'FirstName,Company,City,UnsubscribeURL',
    Channel: 'Email',
    Locale: input.locale,
    Notes: `Generated by AI for ${input.targetAudience}`,
  };

  // 2. Run guardrails
  const hasUnsubscribe = template.Body.toLowerCase().includes('unsubscribe') ||
                         template.Body.includes('{{UnsubscribeURL}}') ||
                         template.TokensCSV?.includes('UnsubscribeURL');
  
  const guardrailResult = await runGuardrails(
    'A-OUT-101',
    'generate-email-template',
    {
      emails: [{
        subject: template.Subject,
        body: template.Body,
        recipientEmail: 'test@example.com',
        hasUnsubscribe: hasUnsubscribe,
      }],
      content: template.Body,
      tone: input.tone,
    },
    sheetsService
  );

  // 3. Create draft job
  const jobId = await createDraftJob(
    sheetsService,
    'A-OUT-101',
    'generate-email-template',
    JSON.stringify(input),
    JSON.stringify({ template, guardrailResult }),
    guardrailResult.passed,
    true
  );

  // 4. Write to draft table
  template.JobID = jobId;
  await sheetsService.writeRows('Outreach_Templates_Draft', [template]);

  await sheetsService.logToSheet(
    'INFO',
    'AI-Outreach',
    `Created email template "${template.Name}" (Job: ${jobId}, Guardrails: ${guardrailResult.passed ? 'PASSED' : 'FAILED'})`
  );

  return {
    jobId,
    template,
    guardrailsPassed: guardrailResult.passed
  };
}
